#ifndef RILL_RPRSSTT
#define RILL_RPRSSTT

#define RILL_PRSSTT_OK
#define RILL_PRSSTT_UNEXPECTED_TOKEN
#define RILL_PRSSTT_UNCLOSED_LIST
#define RILL_PRSSTT_UNCLOSED_HASH
#define RILL_PRSSTT_UNCLOSED_QUOT
#define RILL_PRSSTT_UNCLOSED_WORD
#define RILL_PRSSTT_UNBALANCED_HASH

#endif
