typedef enum RParseError {
    RLE_OK,
    RLE_UNEXPECTED_CHARACTER,
    RLE_INVALID_NUMBER,
    RLE_UNCLOSED_COMMENT,
    RLE_UNCLOSED_STRING,
    RLE_UNCLOSED_LIST,
    RLE_UNCLOSE_LIST,
    RLE_UNCLOSED_HASH,
    RLE_UNBALANCED_HASH,
    RLE_UNCLOSED_WORD,
} RLexError;
