#ifndef RILL_RLEX_ERRORS
#define RILL_RLEX_ERRORS

#define RLXERR_OK
#define RLXERR_INVALID_NUMBER
#define RLXERR_UNTERMINATED_COMMENT
#define RLXERR_UNTERMINATED_STRING
#define RLXERR_UNTERMINATED_LIST
#define RLXERR_UNTERMINATED_HASH
#define RLXERR_UNTERMINATED_QUOTE
#define RLXERR_UNTERMINATED_WORD

#endif
