#ifndef RILL_RLEX_TYPES
#define RILL_RLEX_TYPES

#define RILL_LEXTOK_WHITESPACE    1
#define RILL_LEXTOK_COMMENT       2
#define RILL_LEXTOK_IDENTIFIER    3
#define RILL_LEXTOK_NUMBER        4
#define RILL_LEXTOK_STRING_OPEN   5
#define RILL_LEXTOK_STRING_CLOSE  6
#define RILL_LEXTOK_LIST_OPEN     7
#define RILL_LEXTOK_LIST_CLOSE    8
#define RILL_LEXTOK_HASH_OPEN     9
#define RILL_LEXTOK_HASH_CLOSE   10
#define RILL_LEXTOK_QUOTE_OPEN   11
#define RILL_LEXTOK_QUOTE_CLOSE  12
#define RILL_LEXTOK_WORD_OPEN    13
#define RILL_LEXTOK_WORD_CLOSE   14

#endif
