#ifndef RILL_RLEX_TYPES
#define RILL_RLEX_TYPES

#define RILL_LEXTOK_WHITESPACE      1
#define RILL_LEXTOK_IDENTIFIER      2
#define RILL_LEXTOK_NUMBER          3
#define RILL_LEXTOK_COMMENT_OPEN    4
#define RILL_LEXTOK_COMMENT_CLOSE   5
#define RILL_LEXTOK_STRING_OPEN     6
#define RILL_LEXTOK_STRING_CLOSE    7
#define RILL_LEXTOK_ENUM_OPEN       8
#define RILL_LEXTOK_ENUM_CLOSE      9
#define RILL_LEXTOK_QUOTE_OPEN     10
#define RILL_LEXTOK_QUOTE_CLOSE    11
#define RILL_LEXTOK_COMPILE_OPEN   12
#define RILL_LEXTOK_COMPILE_CLOSE  13

#endif
